steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "frontend"
  # - name: "gcr.io/cloud-builders/npm"
  #   args: ["test"]
  #   dir: 'frontend'
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "frontend"
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "./frontend/build/*", "gs://www.juyoungkim.dev"] # Make sure this path matches the output directory
